"""Generate numodel-coach-template.lua from an empty Coach 7 text model.

Usage (from the bundle root):
    python3 numodel-coach/tools/gen_template.py \
        "coach-proef/0. Leeg model tekst.cmr7" \
        numodel-coach/numodel-coach-template.lua

The input is an empty modelling activity saved by Coach 7 in text mode.
The output is that file's record tree as Lua data, cleaned of
everything that came from the machine or from CMA's sample content:
  * the name of the webcam Coach found (live video source),
  * the instruction text of the empty activity,
  * the model rules, initial values and variable list (filled in by
    numodel-coach for every model).
Developer tool: not shipped (it is not in sourcefiles).
"""
import os, re, sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', 'coach-proef'))
import cma

def lua_str(b):
    """Bytes -> Lua string literal (decimal escapes for non-printables)."""
    parts = []
    for c in b:
        if c in (0x5c, 0x22):                  # backslash, quote
            parts.append('\\' + chr(c))
        elif 0x20 <= c < 0x7f:
            parts.append(chr(c))
        else:
            parts.append('\\%d' % c)
    # A short \ddd escape followed by a digit would swallow it.
    for k in range(len(parts) - 1):
        p = parts[k]
        if p[:1] == '\\' and p[1:].isdigit() and parts[k + 1][:1].isdigit():
            parts[k] = '\\%03d' % int(p[1:])
    return '"' + ''.join(parts) + '"'

def clean(items, path=()):
    out = []
    for it in items:
        if it[0] == 'cont':
            name = it[1].decode('latin-1')
            kids = it[3]
            if not isinstance(kids, bytes):
                kids = clean(kids, path + (name,))
            if name in ('ModelBody', 'ModelInit'):
                kids = []                     # filled per model
            if name == 'VarList':
                kids = [('leaf', b'Number', 0, 2, (0).to_bytes(4, 'little'))]
            out.append(('cont', it[1], it[2], kids))
            continue
        _, name, flag, typ, val = it
        sect = path[-1] if path else ''
        if typ in (4, 6):
            enc = 'cp1252' if typ == 4 else 'utf-16-le'
            prefix = val[:4] if flag == 1 else b''
            text = (val[4:] if flag == 1 else val).decode(enc)
            if 'FaceTime' in text or 'camera' in text.lower():
                for cam in ('FaceTime HD-camera', 'FaceTime HD Camera'):
                    text = text.replace(cam, '')
            if sect == 'NewText\x00Instructie':
                text = ''
            if sect == 'HTMLText\x00Instructie':
                text = '<body><p>&nbsp;</p></body>'
            val = prefix + text.encode(enc)
        out.append(('leaf', name, flag, typ, val))
    return out

def emit(items, ind):
    lines = []
    pad = '  ' * ind
    for it in items:
        if it[0] == 'cont':
            _, name, hdr, kids = it
            if isinstance(kids, bytes):
                lines.append(f'{pad}{{ "c", {lua_str(name)}, {lua_str(hdr)}, raw = {lua_str(kids)} }},')
            else:
                lines.append(f'{pad}{{ "c", {lua_str(name)}, {lua_str(hdr)}, {{')
                lines += emit(kids, ind + 1)
                lines.append(f'{pad}}} }},')
        else:
            _, name, flag, typ, val = it
            lines.append(f'{pad}{{ "l", {lua_str(name)}, {flag}, {typ}, {lua_str(val)} }},')
    return lines

def release():
    """release_tag and release_date from tagsetup.lua (bundle root)."""
    t = open(os.path.join(os.path.dirname(__file__), '..', '..', 'tagsetup.lua')).read()
    tag = re.search(r'release_tag\s*=\s*"([^"]+)"', t).group(1)
    date = re.search(r'release_date\s*=\s*"([^"]+)"', t).group(1)
    return tag, date

def main(src, dst):
    magic, items = cma.parse(open(src, 'rb').read())
    items = clean(items)
    tag, date = release()
    head = [
        f'-- numodel-coach-template.lua  v{tag}  {date}',
        '-- GENERATED by numodel-coach/tools/gen_template.py -- do not edit.',
        '--',
        '-- Record tree of an empty Coach 7 modelling activity in text mode,',
        '-- cleaned of machine-specific data (webcam name) and sample content',
        '-- (instruction text).  ModelBody, ModelInit and VarList are empty;',
        '-- numodel-coach fills them for each model.',
        '--   { "c", name, header, { children } }   container',
        '--   { "c", name, header, raw = bytes }    opaque container',
        '--   { "l", name, flag, type, value }      leaf (type: 0 byte,',
        '--        2 int32, 3 extended, 4 ANSI text, 6 UTF-16LE text)',
        '',
        'return {',
        f'  magic = {lua_str(magic)},',
        '  items = {',
    ]
    body = emit(items, 2)
    tail = ['  },', '}', '']
    open(dst, 'w').write('\n'.join(head + body + tail))
    print(f'{dst}: {len(body)} lines')

if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
