#!/usr/bin/env texlua

-- Build configuration for the numodel-coach module (within
-- numodel-bundle).  Most settings are inherited from the bundle
-- build.lua; this file only defines what is specific to this module.

bundle  = "numodel-bundle"
module  = "numodel-coach"
maindir = ".."

-- Shared release tag/date, see ../tagsetup.lua.
dofile(maindir .. "/tagsetup.lua")

-- numodel-coach builds on numodel's Lua API, so LuaLaTeX throughout.
checkengines = {"luatex"}
stdengine    = "luatex"
checkformat  = "latex"
typesetexe   = "lualatex"
unpackexe    = "luatex"
typesetruns  = 3

-- The two Lua files are hand-written / generated companions of the
-- .sty, not docstrip output, so they are copied through as sources.
-- numodel-coach-template.lua is generated by tools/gen_template.py.
sourcefiles = {
  "numodel-coach.dtx",
  "numodel-coach.ins",
  "numodel-coach.lua",
  "numodel-coach-template.lua",
  "numodel-coach-manual.tex",
}
installfiles = {
  "numodel-coach.sty",
  "numodel-coach.lua",
  "numodel-coach-template.lua",
}
typesetfiles = {"numodel-coach-manual.tex"}
textfiles    = {}

-- numodel itself (sty, defs, lua) must be visible to tests and the
-- manual; l3build unpacks the sibling module into the sandbox.
checkdeps   = {maindir .. "/numodel", maindir .. "/numodel-plot"}
typesetdeps = {maindir .. "/numodel", maindir .. "/numodel-plot"}
unpackdeps  = {}

testfiledir = "testfiles"
